#ifndef __POLVERINE_PRJ_CFG_H
#define __POLVERINE_PRJ_CFG_H

#define PVLN_CFG_BSEC_OUTPUT_UPDATE_GATED_BY_BMV080 true
#define PLVN_CFG_BSEC_LOOP_DELAY_TIME_MS    50

#define PLVN_CFG_BMV080_DUTY_CYCLE_PERIOD_S 30

#define PLVN_CFG_BMV080_CONNECTIVITY_USB    true
#define PLVN_CFG_TEMP_PROFILE_CLIENT_ID     1

#endif
